/** A&S Quik Pik — product catalog (~65 items). Prices are suggested / may vary in store. */
window.QUIK_PIK_PRODUCTS = [
  { id: "ic-friendlys-vanilla", name: "Friendly's Vanilla Cup", brand: "Friendly's", category: "ice-cream", price: 2.49, image: "images/products/friendlys-vanilla.svg", tags: ["frozen", "dessert"] },
  { id: "ic-friendlys-chocolate", name: "Friendly's Chocolate Cup", brand: "Friendly's", category: "ice-cream", price: 2.49, image: "images/products/friendlys-chocolate.svg", tags: ["frozen"] },
  { id: "ic-popsicle-classic", name: "Popsicle Classic Assorted", brand: "Popsicle", category: "ice-cream", price: 1.99, image: "images/products/popsicle-classic.svg", tags: ["frozen"] },
  { id: "ic-goodhumor-bar", name: "Good Humor Chocolate Eclair", brand: "Good Humor", category: "ice-cream", price: 2.29, image: "images/products/goodhumor-eclair.svg", tags: ["frozen"] },
  { id: "ic-goodhumor-strawberry", name: "Good Humor Strawberry Shortcake", brand: "Good Humor", category: "ice-cream", price: 2.29, image: "images/products/goodhumor-strawberry.svg", tags: ["frozen"] },
  { id: "ic-popsicle-firecracker", name: "Popsicle Firecracker", brand: "Popsicle", category: "ice-cream", price: 1.79, image: "images/products/popsicle-firecracker.svg", tags: ["frozen"] },
  { id: "cd-halls-mentho", name: "Halls Mentho-Lyptus", brand: "Halls", category: "candy", price: 2.49, image: "images/products/halls-menthol.svg", tags: ["cough drops"] },
  { id: "cd-altoids-peppermint", name: "Altoids Peppermint", brand: "Altoids", category: "candy", price: 2.99, image: "images/products/altoids-peppermint.svg", tags: ["mints"] },
  { id: "cd-reeses-cups", name: "Reese's Peanut Butter Cups", brand: "Reese's", category: "candy", price: 1.79, image: "images/products/reeses-cups.svg", tags: ["chocolate"] },
  { id: "cd-kitkat", name: "KitKat Bar", brand: "KitKat", category: "candy", price: 1.69, image: "images/products/kitkat.svg", tags: ["chocolate"] },
  { id: "cd-snickers", name: "Snickers Bar", brand: "Snickers", category: "candy", price: 1.69, image: "images/products/snickers.svg", tags: ["chocolate"] },
  { id: "cd-extra-spearmint", name: "Extra Spearmint Gum", brand: "Extra", category: "candy", price: 1.99, image: "images/products/extra-gum.svg", tags: ["gum"] },
  { id: "cd-airheads", name: "Airheads Assorted", brand: "Airheads", category: "candy", price: 1.49, image: "images/products/airheads.svg", tags: ["chewy"] },
  { id: "cd-skittles", name: "Skittles Original", brand: "Skittles", category: "candy", price: 1.79, image: "images/products/skittles.svg", tags: ["fruit"] },
  { id: "cd-twix", name: "Twix Bar", brand: "Twix", category: "candy", price: 1.69, image: "images/products/twix.svg", tags: ["chocolate"] },
  { id: "sn-utz-chips", name: "Utz Potato Chips", brand: "Utz", category: "snacks", price: 2.49, image: "images/products/utz-chips.svg", tags: ["chips"] },
  { id: "sn-pringles-original", name: "Pringles Original", brand: "Pringles", category: "snacks", price: 2.29, image: "images/products/pringles.svg", tags: ["chips"] },
  { id: "sn-slimjim", name: "Slim Jim Original", brand: "Slim Jim", category: "snacks", price: 1.49, image: "images/products/slimjim.svg", tags: ["meat"] },
  { id: "sn-andycapps", name: "Andy Capp's Hot Fries", brand: "Andy Capp's", category: "snacks", price: 1.99, image: "images/products/andycapps.svg", tags: ["chips"] },
  { id: "sn-cheetos", name: "Cheetos Crunchy", brand: "Cheetos", category: "snacks", price: 2.29, image: "images/products/cheetos.svg", tags: ["chips"] },
  { id: "sn-doritos", name: "Doritos Nacho Cheese", brand: "Doritos", category: "snacks", price: 2.49, image: "images/products/doritos.svg", tags: ["chips"] },
  { id: "vp-airis-mega-coolmint", name: "Airis Mega Cool Mint", brand: "Airis", category: "vapes", price: 12.99, ageRestricted: true, image: "images/products/airis-mega.svg", tags: ["disposable"] },
  { id: "vp-crownbar-blueberry", name: "Crown Bar Pro Blueberry Ice", brand: "Crown Bar", category: "vapes", price: 18.99, ageRestricted: true, image: "images/products/crownbar-blueberry.svg", tags: ["disposable"] },
  { id: "vp-crownbar-watermelon", name: "Crown Bar Pro Watermelon Ice", brand: "Crown Bar", category: "vapes", price: 18.99, ageRestricted: true, image: "images/products/crownbar-watermelon.svg", tags: ["disposable"] },
  { id: "vp-crownbar-mango", name: "Crown Bar Pro Mango Peach", brand: "Crown Bar", category: "vapes", price: 18.99, ageRestricted: true, image: "images/products/crownbar-mango.svg", tags: ["disposable"] },
  { id: "vp-zyn-coolmint", name: "ZYN Cool Mint 6mg", brand: "ZYN", category: "vapes", price: 5.99, ageRestricted: true, image: "images/products/zyn-coolmint.svg", tags: ["nicotine pouch"] },
  { id: "vp-zyn-citrus", name: "ZYN Citrus 3mg", brand: "ZYN", category: "vapes", price: 5.99, ageRestricted: true, image: "images/products/zyn-citrus.svg", tags: ["nicotine pouch"] },
  { id: "vp-raz-blue", name: "RAZ TN9000 Blue Razz Ice", brand: "RAZ", category: "vapes", price: 16.99, ageRestricted: true, image: "images/products/raz-blue.svg", tags: ["disposable"] },
  { id: "vp-geekbar-melon", name: "Geek Bar Pulse Melon Ice", brand: "Geek Bar", category: "vapes", price: 17.99, ageRestricted: true, image: "images/products/geekbar-melon.svg", tags: ["disposable"] },
  { id: "vp-geekbar-grape", name: "Geek Bar Pulse Grape Ice", brand: "Geek Bar", category: "vapes", price: 17.99, ageRestricted: true, image: "images/products/geekbar-grape.svg", tags: ["disposable"] },
  { id: "tb-backwoods-honey", name: "Backwoods Honey Berry", brand: "Backwoods", category: "tobacco", price: 8.99, ageRestricted: true, image: "images/products/backwoods-honey.svg", tags: ["cigarillo"] },
  { id: "tb-backwoods-sweet", name: "Backwoods Sweet Aromatic", brand: "Backwoods", category: "tobacco", price: 8.99, ageRestricted: true, image: "images/products/backwoods-sweet.svg", tags: ["cigarillo"] },
  { id: "tb-backwoods-russian", name: "Backwoods Russian Cream", brand: "Backwoods", category: "tobacco", price: 8.99, ageRestricted: true, image: "images/products/backwoods-russian.svg", tags: ["cigarillo"] },
  { id: "tb-marlboro-red", name: "Marlboro Red (Pack)", brand: "Marlboro", category: "tobacco", price: 12.99, ageRestricted: true, image: "images/products/marlboro-red.svg", tags: ["cigarettes"] },
  { id: "tb-marlboro-gold", name: "Marlboro Gold (Pack)", brand: "Marlboro", category: "tobacco", price: 12.99, ageRestricted: true, image: "images/products/marlboro-gold.svg", tags: ["cigarettes"] },
  { id: "tb-dutch-masters", name: "Dutch Masters Palma", brand: "Dutch Masters", category: "tobacco", price: 6.99, ageRestricted: true, image: "images/products/dutch-masters.svg", tags: ["cigar"] },
  { id: "tb-dutch-honey", name: "Dutch Masters Honey", brand: "Dutch Masters", category: "tobacco", price: 6.99, ageRestricted: true, image: "images/products/dutch-honey.svg", tags: ["cigar"] },
  { id: "ac-raw-papers", name: "RAW Classic Rolling Papers", brand: "RAW", category: "accessories", price: 2.49, ageRestricted: true, image: "images/products/raw-papers.svg", tags: ["papers"] },
  { id: "ac-raw-cones", name: "RAW Pre-Rolled Cones", brand: "RAW", category: "accessories", price: 3.99, ageRestricted: true, image: "images/products/raw-cones.svg", tags: ["cones"] },
  { id: "ac-zigzag", name: "Zig-Zag Orange Papers", brand: "Zig-Zag", category: "accessories", price: 1.99, ageRestricted: true, image: "images/products/zigzag.svg", tags: ["papers"] },
  { id: "ac-juicyjays", name: "Juicy Jay's Rolling Papers", brand: "Juicy Jay's", category: "accessories", price: 2.29, ageRestricted: true, image: "images/products/juicyjays.svg", tags: ["papers"] },
  { id: "ac-blink-torch", name: "Blink Torch Lighter", brand: "Blink", category: "accessories", price: 9.99, ageRestricted: true, image: "images/products/blink-torch.svg", tags: ["lighter"] },
  { id: "ac-grinder", name: "Metal Herb Grinder 4-Piece", brand: "Generic", category: "accessories", price: 12.99, ageRestricted: true, image: "images/products/grinder.svg", tags: ["grinder"] },
  { id: "hk-adalya-love", name: "Adalya Love 66", brand: "Adalya", category: "hookah", price: 14.99, ageRestricted: true, image: "images/products/adalya-love.svg", tags: ["shisha"] },
  { id: "hk-adalya-double", name: "Adalya Double Melon", brand: "Adalya", category: "hookah", price: 14.99, ageRestricted: true, image: "images/products/adalya-melon.svg", tags: ["shisha"] },
  { id: "hk-alfakher-mint", name: "Al Fakher Mint", brand: "Al Fakher", category: "hookah", price: 12.99, ageRestricted: true, image: "images/products/alfakher-mint.svg", tags: ["shisha"] },
  { id: "hk-alfakher-grape", name: "Al Fakher Two Apples", brand: "Al Fakher", category: "hookah", price: 12.99, ageRestricted: true, image: "images/products/alfakher-apples.svg", tags: ["shisha"] },
  { id: "hk-set-starter", name: "Hookah Starter Set", brand: "Store Select", category: "hookah", price: 49.99, ageRestricted: true, image: "images/products/hookah-set.svg", tags: ["set"] },
  { id: "gl-cola-bong", name: "Cola Bottle Bong", brand: "Novelty", category: "glass", price: 29.99, ageRestricted: true, image: "images/products/cola-bong.svg", tags: ["bong"] },
  { id: "gl-beaker-bong", name: "Beaker Base Water Pipe", brand: "Generic", category: "glass", price: 39.99, ageRestricted: true, image: "images/products/beaker-bong.svg", tags: ["bong"] },
  { id: "gl-spoon-pipe", name: "Spoon Hand Pipe", brand: "Generic", category: "glass", price: 14.99, ageRestricted: true, image: "images/products/spoon-pipe.svg", tags: ["pipe"] },
  { id: "gl-sherlock", name: "Sherlock Style Pipe", brand: "Generic", category: "glass", price: 19.99, ageRestricted: true, image: "images/products/sherlock-pipe.svg", tags: ["pipe"] },
  { id: "fr-blunteffects", name: "Blunteffects Air Freshener", brand: "Blunteffects", category: "fragrance", price: 4.99, image: "images/products/blunteffects.svg", tags: ["air freshener"] },
  { id: "fr-orva", name: "ORVA Fragrance Spray", brand: "ORVA", category: "fragrance", price: 6.99, image: "images/products/orva.svg", tags: ["spray"] },
  { id: "fr-ampliscent", name: "Ampliscent Car Freshener", brand: "Ampliscent", category: "fragrance", price: 5.49, image: "images/products/ampliscent.svg", tags: ["car"] },
  { id: "fr-paris-royale", name: "Paris Royale Cologne Sample", brand: "Paris Royale", category: "fragrance", price: 9.99, image: "images/products/paris-royale.svg", tags: ["cologne"] },
  { id: "ph-wegacell-usb-c", name: "WEGACELL USB-C Cable", brand: "WEGACELL", category: "phone", price: 9.99, image: "images/products/wegacell-usbc.svg", tags: ["cable"] },
  { id: "ph-wegacell-lightning", name: "WEGACELL Lightning Cable", brand: "WEGACELL", category: "phone", price: 9.99, image: "images/products/wegacell-lightning.svg", tags: ["cable"] },
  { id: "ph-wegacell-charger", name: "WEGACELL Wall Charger", brand: "WEGACELL", category: "phone", price: 14.99, image: "images/products/wegacell-charger.svg", tags: ["charger"] },
  { id: "lt-ct-lottery", name: "CT Lottery Tickets", brand: "Connecticut Lottery", category: "lottery", price: null, informational: true, image: "images/products/ct-lottery.svg", tags: ["scratchers", "draw games"] }
];

window.QUIK_PIK_CATEGORIES = [
  { id: "all", label: "All Products", restricted: false },
  { id: "ice-cream", label: "Ice Cream", restricted: false },
  { id: "candy", label: "Candy & Gum", restricted: false },
  { id: "snacks", label: "Snacks", restricted: false },
  { id: "vapes", label: "Vapes & Pouches", restricted: true },
  { id: "tobacco", label: "Tobacco", restricted: true },
  { id: "accessories", label: "Papers & Accessories", restricted: true },
  { id: "hookah", label: "Hookah", restricted: true },
  { id: "glass", label: "Glass", restricted: true },
  { id: "fragrance", label: "Fragrance", restricted: false },
  { id: "phone", label: "Phone Accessories", restricted: false },
  { id: "lottery", label: "Lottery", restricted: false }
];
